name: Python Tests

on:
  push:
    branches:
      - main  # Exécuter les tests lors d'un push sur la branche main
  pull_request:
    branches:
      - main  # Exécuter les tests pour les pull requests vers main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Récupère le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Vous pouvez spécifier la version de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installez les dépendances du projet
        pip install pytest pytest-cov  # Installez Pytest et les outils de couverture

    - name: Run tests
      run: |
        pytest --cov=app_analyse_musicale  # Exécute les tests avec mesure de la couverture

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: .coverage
    - name: Upload artifact
      uses: actions/upload-artifact@v3


