name: unit-tests

on:
  push:
    branches: 
      - main  # Déclenche sur un push vers la branche main
  pull_request:
    branches: 
      - main  # Déclenche pour les pull requests vers la branche main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Vérifie le code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'  # Spécifie la version de Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances à partir de requirements.txt

    - name: Install Pytest
      run: |
        pip install pytest  # Installe pytest pour exécuter les tests

    - name: Run tests
      run: |
        pytest  # Exécute les tests avec pytest
